**TensorFlow Basics**

In [3]:
import tensorflow as tf

In [5]:
print(tf.__version__)

2.19.0


In [6]:
#Creating Tensor with constant
#function here that we can use to create
scalar=tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [7]:
scalar.ndim

0

In [9]:
import numpy as np

In [15]:
matrix = tf.constant([[5, 9], [9, 11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  9],
       [ 9, 11]], dtype=int32)>

In [16]:
matrix.ndim

2

In [12]:
second_matrix=tf.constant([[5,7],
                          [3,8],
                          [3,9],
                          [4,2],
                          [8,6]])

In [17]:
second_matrix

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[5, 7],
       [3, 8],
       [3, 9],
       [4, 2],
       [8, 6]], dtype=int32)>

In [18]:
second_matrix.ndim

2

In [19]:
third_matrix=tf.constant(
    [[
        [1,2,3],
        [2,4,5],
        [7,9,3],
        [10,4,5],
        [11,2,3],
        [2,4,15]
    ]]
)
third_matrix

<tf.Tensor: shape=(1, 6, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  4,  5],
        [ 7,  9,  3],
        [10,  4,  5],
        [11,  2,  3],
        [ 2,  4, 15]]], dtype=int32)>

In [20]:
third_matrix.ndim

3

In [21]:
second_matrix=tf.constant([[5.6,7.3],
                          [3.45,8.25],
                          [3.11,9.23],
                          [4.34,2.34],
                          [8.4,6.23]],dtype=tf.float16)
second_matrix

<tf.Tensor: shape=(5, 2), dtype=float16, numpy=
array([[5.6 , 7.3 ],
       [3.45, 8.25],
       [3.11, 9.23],
       [4.34, 2.34],
       [8.4 , 6.23]], dtype=float16)>

In [22]:
# single Number that means scalar
scalar=tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [23]:
# number with direction
vector=tf.constant([10,10,20,30])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 10, 20, 30], dtype=int32)>

In [24]:
# 2-D array of numbers
matrix=tf.constant([[10,20],[30,40]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [25]:
# Tensor : n-dimensional array of numbers (n=0,n=1,n=2....)
tensor=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [26]:
# Find the shape, dimension,rank and size of the tensors
print('Scalar Information :')
print('Shape: ',scalar.shape)
print('Dimension:',scalar.ndim)
print('Rank: ',tf.rank(scalar).numpy())
print('Size: ',tf.size(scalar))

Scalar Information :
Shape:  ()
Dimension: 0
Rank:  0
Size:  tf.Tensor(1, shape=(), dtype=int32)


In [28]:
print('Vector Information :')
print('Shape: ',vector.shape)
print('Dimension:',vector.ndim)
print('Rank: ',tf.rank(vector).numpy())
print('Size: ',tf.size(vector))

Vector Information :
Shape:  (4,)
Dimension: 1
Rank:  1
Size:  tf.Tensor(4, shape=(), dtype=int32)


In [29]:
print('Matrix Information :')
print('Shape: ',matrix.shape)
print('Dimension:',matrix.ndim)
print('Rank: ',tf.rank(matrix).numpy())
print('Size: ',tf.size(matrix))

Matrix Information :
Shape:  (2, 2)
Dimension: 2
Rank:  2
Size:  tf.Tensor(4, shape=(), dtype=int32)


In [30]:
print('Tensor Information :')
print('Shape: ',tensor.shape)
print('Dimension:',tensor.ndim)
print('Rank: ',tf.rank(tensor).numpy())
print('Size: ',tf.size(tensor))

Tesnor Information :
Shape:  (2, 2, 2)
Dimension: 3
Rank:  3
Size:  tf.Tensor(8, shape=(), dtype=int32)


In [31]:
# Creating Tensor using Variable
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [32]:
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [33]:
changeable_tensor[1].assign(15)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 15], dtype=int32)>

In [35]:
changeable_tensor[1].assign(75)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 75], dtype=int32)>

In [37]:
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [38]:
#unchangeable_tensor[0].assign(12)
#unchangeable_tensor
#this will be an error because you can't change constant tensor. They are Immutable i.e unchangable

In [40]:
# Random Tensor
random_tensor=tf.random.Generator.from_seed(42)
random_tensor=random_tensor.normal(shape=(3,2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [41]:
random_tensor_2=tf.random.uniform(shape=(300,150),minval=0,maxval=1)
random_tensor_2

<tf.Tensor: shape=(300, 150), dtype=float32, numpy=
array([[0.2968818 , 0.37123942, 0.55488586, ..., 0.67497396, 0.08628619,
        0.7027036 ],
       [0.15481007, 0.2274344 , 0.11538744, ..., 0.4490186 , 0.9058639 ,
        0.30911422],
       [0.03278363, 0.3057338 , 0.17692089, ..., 0.7251091 , 0.57939017,
        0.966625  ],
       ...,
       [0.5726168 , 0.45551574, 0.9026729 , ..., 0.4279822 , 0.2809751 ,
        0.0635215 ],
       [0.78197014, 0.38471472, 0.5515474 , ..., 0.5790422 , 0.8317567 ,
        0.209813  ],
       [0.43522072, 0.17266059, 0.2838701 , ..., 0.8799151 , 0.09592235,
        0.6516677 ]], dtype=float32)>

In [42]:
random_tensor_3=tf.random.Generator.from_seed(42)
random_tensor_3=random_tensor_3.normal(shape=(3,2))
random_tensor_4=tf.random.Generator.from_seed(42)
random_tensor_4=random_tensor_4.normal(shape=(3,2))
random_tensor_3,random_tensor_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [43]:
random_tensor_3=tf.random.Generator.from_seed(42)
random_tensor_3=random_tensor_3.normal(shape=(3,2))
random_tensor_4=tf.random.Generator.from_seed(15)
random_tensor_4=random_tensor_4.normal(shape=(3,2))
random_tensor_3,random_tensor_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.33149973, -0.5445254 ],
        [ 1.5222508 ,  0.59303206],
        [-0.63509274,  0.3703566 ]], dtype=float32)>)

In [47]:
# creating tersors using zeros
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.int16)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [48]:
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.float32)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [51]:
# Tensors for all
tensor_ones=tf.ones(shape=(3,4),dtype=tf.dtypes.int16)
tensor_ones

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)>

In [54]:
import numpy as np
numpy_Array=np.arange(1,25,dtype=np.int16)
numpy_Array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [55]:
tensor_numpy=tf.constant(numpy_Array,shape=(2,3,4))
tensor_numpy

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

In [56]:
print('Tensor Information :')
print('Shape: ',tensor_numpy.shape)
print('Dimension:',tensor_numpy.ndim)
print('Rank: ',tf.rank(tensor_numpy).numpy())
print('Size: ',tf.size(tensor_numpy))
print('DataType of elements: ',tensor_numpy.dtype)
print('Element along axis 0: ',tensor_numpy.shape[0])
print('Element along axis 1: ',tensor_numpy.shape[1])
print('Element along axis 2: ',tensor_numpy.shape[2])
print('Total number of elements: ',tf.size(tensor_numpy).numpy())

Tesnor Information :
Shape:  (2, 3, 4)
Dimension: 3
Rank:  3
Size:  tf.Tensor(24, shape=(), dtype=int32)
DataType of elements:  <dtype: 'int16'>
Element along axis 0:  2
Element along axis 1:  3
Element along axis 2:  4
Total number of elements:  24


In [57]:
# working with items of each dimension
tensor_numpy[:3,:3,:3]

<tf.Tensor: shape=(2, 3, 3), dtype=int16, numpy=
array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]]], dtype=int16)>

In [58]:
tensor_numpy[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int16, numpy=
array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]], dtype=int16)>

**Arithmetic Operations with tensors**
  - Add
  - Sub
  - Multi
  - Div

In [60]:
tensor_one=tf.constant([[11,9],[2,5]])
tensor_one

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  9],
       [ 2,  5]], dtype=int32)>

In [63]:
#tensor_one+15
tf.add(tensor_one,15)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 24],
       [17, 20]], dtype=int32)>

In [64]:
#tensor_one-5
tf.subtract(tensor_one,5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  4],
       [-3,  0]], dtype=int32)>

In [65]:
#tensor_one*2
tf.multiply(tensor_one,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 18],
       [ 4, 10]], dtype=int32)>

In [66]:
#tensor_one/5
tf.divide(tensor_one,5)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2.2, 1.8],
       [0.4, 1. ]])>

In [69]:
tensor_new=tf.square(tensor_one)
tensor_new

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  81],
       [  4,  25]], dtype=int32)>

In [70]:
second_matrix=tf.constant([[8,16],
                          [64,8.25],
                          [625,9.25],
                          [125,2.34],
                          [169,144]])
second_matrix

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[  8.  ,  16.  ],
       [ 64.  ,   8.25],
       [625.  ,   9.25],
       [125.  ,   2.34],
       [169.  , 144.  ]], dtype=float32)>

In [71]:
tf.sqrt(second_matrix)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 2.828427 ,  4.       ],
       [ 8.       ,  2.8722813],
       [25.       ,  3.0413814],
       [11.18034  ,  1.5297059],
       [13.       , 12.       ]], dtype=float32)>

**Exercise**
Create two tensors with random values between 0 and 1, shape is [6,300]

Find out the following details:
  - Number of Elements
  - Size
  - Rank
  - Shape



In [74]:
tensor1 = np.random.rand(6, 300)
tensor2 = np.random.rand(6, 300)

print('Tensor1 Information :')
print('Shape: ',tensor1.shape)
print('Dimension:',tensor1.ndim)
print('Rank: ',tf.rank(tensor1).numpy())
print('Size: ',tf.size(tensor1))

print('\nTensor2 Information :')
print('Shape: ',tensor2.shape)
print('Dimension:',tensor2.ndim)
print('Rank: ',tf.rank(tensor2).numpy())
print('Size: ',tf.size(tensor2))

Tensor1 Information :
Shape:  (6, 300)
Dimension: 2
Rank:  2
Size:  tf.Tensor(1800, shape=(), dtype=int32)

Tensor2 Information :
Shape:  (6, 300)
Dimension: 2
Rank:  2
Size:  tf.Tensor(1800, shape=(), dtype=int32)
