# Numpy Introduvtion and usage
## we will use NumPy in Jupyter Noteboook

# One Dimensional Array (1-D)

In [2]:
import numpy as np

In [3]:
array1=np.array([10,20,30,40,50])

In [4]:
print(array1)

[10 20 30 40 50]


# Two Dimensional Array (2-D)

In [8]:
array_two=np.array([[10,20,30],[40,50,70]])

In [10]:
print(array_two)

[[10 20 30]
 [40 50 70]]


# Three Dimensional Array (3-D)

In [12]:
array_three=np.array([[[10,20,30],[40,50,70]],[[10,20,30],[40,50,70]]])

In [13]:
print(array_three)

[[[10 20 30]
  [40 50 70]]

 [[10 20 30]
  [40 50 70]]]


## Find out Dimension of NumPy Array

In [16]:
print('First Array Dimension: \t', array1.ndim)

First Array Dimension: 	 1


In [17]:
print('Second Array Dimension: \t', array_two.ndim)

Second Array Dimension: 	 2


In [18]:
print('Third Array Dimension: \t', array_three.ndim)

Third Array Dimension: 	 3


# Write an array of 5 students mark using NumPy
## Marks are: 80,70,75,99,89

In [19]:
array_students=np.array([80,70,75,99,89])

In [20]:
print(array_students)

[80 70 75 99 89]


# Write an array: to take marks of 5 students in 3 subjects using NumPy
## Math, English, Chemistry
## [[50,45,49],[40,42,45],[35,40,46],[39,40,45],[48,40,40]]

In [21]:
array_marks_subject=np.array([[50,45,49],[40,42,45],[35,40,46],[39,40,45],[48,40,40]])
print('2D Array Example')
print(array_marks_subject)

2D Array Example
[[50 45 49]
 [40 42 45]
 [35 40 46]
 [39 40 45]
 [48 40 40]]


# Write an array: to take marks of 4 students in 3 subjects for 2 semesters using NumPy
    ## Students name are:'Jennie','Lalisa','Jisoo','Rose'
    ## Math, English, Chemistry
    ## Two Semester : Sem1 , Sem2
    ## 4*3*2
    ## [[[85,88],[78,82],[90,95]],[[76,70],[40,45],[90,90]],[[80,86],[78,82],[90,95]],[[85,88],[78,82],[70,90]]]

In [22]:
array_students_semester=np.array([[[85,88],[78,82],[90,95]],
                                  [[76,70],[40,45],[90,90]],
                                  [[80,86],[78,82],[90,95]],
                                  [[85,88],[78,82],[70,90]]])

In [23]:
print(array_students_semester)

[[[85 88]
  [78 82]
  [90 95]]

 [[76 70]
  [40 45]
  [90 90]]

 [[80 86]
  [78 82]
  [90 95]]

 [[85 88]
  [78 82]
  [70 90]]]


# Write an array: to take weather of 2 cities in 3 day for 3 times in a day
    ## Cities name are:'Kl','Tokyo'
    ## Saturday, Sunday, Monday
    ## Morning, Noon, Evening
# Create one 3D Array using numPy

In [37]:
weather=np.array([[[25,-8],[25,-2],[23,-5]],
                  [[22,0],[28,-3],[29,4]],
                  [[20,2],[30,2],[28,5]]])

In [38]:
print(weather)

[[[25 -8]
  [25 -2]
  [23 -5]]

 [[22  0]
  [28 -3]
  [29  4]]

 [[20  2]
  [30  2]
  [28  5]]]


In [40]:
weathers=np.array([[[25,28,27],[25,22,22],[23,25,23]],
                  [[-8,0,1],[8,-3,2],[9,4,3]]])

In [41]:
print(weathers)

[[[25 28 27]
  [25 22 22]
  [23 25 23]]

 [[-8  0  1]
  [ 8 -3  2]
  [ 9  4  3]]]


# Basic Information
    ##shape: rows and columns
    ##size: number of elements
    ##dimension: return dimension 1,2,3
    ##data type: return stored data values type

In [42]:
print(array1)

[10 20 30 40 50]


In [43]:
print('Shape of array1 : ',array1.shape)

Shape of array1 :  (5,)


In [44]:
print('Size of array1 : ',array1.size)

Size of array1 :  5


In [45]:
print('Dimension of array1 : ',array1.ndim)

Dimension of array1 :  1


In [46]:
print('Data type of array1 : ',array1.dtype)

Data type of array1 :  int64


In [55]:
students=np.array(['Jennie binti Abdullah','Lalisa','Jisoo','Rose','IU'])

In [56]:
print(students)

['Jennie binti Abdullah' 'Lalisa' 'Jisoo' 'Rose' 'IU']


In [57]:
print('Shape of array1 : ',students.shape)

Shape of array1 :  (5,)


In [58]:
print('Shape of array1 : ',students.size)

Shape of array1 :  5


In [59]:
print('Shape of array1 : ',students.dtype)

Shape of array1 :  <U21


# Mathermatical Operation

In [60]:
print(array1)

[10 20 30 40 50]


In [61]:
total=np.sum(array1)

In [62]:
print(total)

150


In [64]:
print('Average: ',np.mean(array1))

Average:  30.0


In [65]:
print('Min: ',np.min(array1))

Min:  10


In [66]:
print('Max: ',np.max(array1))

Max:  50


In [67]:
print('Index of Min: ',np.argmin(array1))

Index of Min:  0


In [69]:
print('Index of Max: ',np.argmax(array1))

Index of Max:  4


In [78]:
our_arr=np.array([100,200,300,7000,400,500,300,1900,600])

In [79]:
print(our_arr)

[ 100  200  300 7000  400  500  300 1900  600]


# Searching and Sorting Example in 1D Array

In [80]:
sorted_arr=np.sort(our_arr)
print('***Sorted Array***')
print(sorted_arr)

***Sorted Array***
[ 100  200  300  300  400  500  600 1900 7000]


In [81]:
print('Any item greater than 500? : ',np.any(sorted_arr>500))

Any item greater than 500? :  True


In [87]:
print('All greater than 500? : ',np.all(sorted_arr>500))

All greater than 500? :  False


In [83]:
print('All greater than 99? : ',np.any(sorted_arr>99))

All greater than 99? :  True


In [85]:
print('Where values > 500? : ',np.where(sorted_arr>500))

Where values > 500? :  (array([6, 7, 8]),)


In [86]:
print('All number greater than 500? : ')
for num in np.where(sorted_arr>500):
    print(num)

All number greater than 500? : 
[6 7 8]


In [88]:
print(our_arr)

[ 100  200  300 7000  400  500  300 1900  600]


In [89]:
print(min(our_arr))

100


In [91]:
print('Index of min: ',np.argmin(our_arr))

Index of min:  0


In [95]:
print('Index of max: ',np.argmax(our_arr))

Index of max:  3


In [94]:
print('All number greater than 500? : ')
for num in sorted_arr>500:
    print(num)

All number greater than 500? : 
False
False
False
False
False
False
True
True
True


In [96]:
selected_values=sorted_arr[sorted_arr>500]

In [97]:
print(selected_values)

[ 600 1900 7000]


In [98]:
for num in selected_values:
    print(num)

600
1900
7000


# this is the shorter version (kat atas mcm explanation dia)

In [99]:
for num in sorted_arr[sorted_arr>500]:
    print(num)

600
1900
7000


In [100]:
print (' ',sorted_arr[sorted_arr>500])

  [ 600 1900 7000]


## or can code this way to get the non sorted:
    ## for num in our_arr[our_arr>500]:
            print(num)

In [101]:
for num in our_arr[our_arr>500]:
    print(num)

7000
1900
600


# Slicing 1 D Array
    ## 1. To take elements from starting index to end index
    ## 2. e.g [start:end]

In [107]:
print(sorted_arr)

[ 100  200  300  300  400  500  600 1900 7000]


In [109]:
slice_sorted_arr=sorted_arr[1:3]
print(slice_sorted_arr)

[200 300]


# starting from an index and going till last

In [110]:
print(sorted_arr[3:])

[ 300  400  500  600 1900 7000]


In [111]:
print(sorted_arr[:4])

[100 200 300 300]


In [112]:
print(sorted_arr[:5])

[100 200 300 300 400]


# step
    ##[start:end:step]
    ##[step: every step element

In [113]:
our_slice=sorted_arr[1:6:2]
print(our_slice)

[200 300 500]


In [116]:
print('Original Sorted Array')
print(sorted_arr)
print('Every Third Element')
every_third_element=sorted_arr[::2]
print(every_third_element)

Original Sorted Array
[ 100  200  300  300  400  500  600 1900 7000]
Every Third Element
[ 100  300  400  600 7000]


# Slice Reverse

In [117]:
print('Original Sorted Array')
print(sorted_arr)
print('Reverse Array: ',sorted_arr[::-1])


Original Sorted Array
[ 100  200  300  300  400  500  600 1900 7000]
Reverse Array:  [7000 1900  600  500  400  300  300  200  100]


    ## print('Reverse Array: ')
    ## print (sorted_arr[::-1])
    ## same thing in two lines

In [119]:
print('Reverse Array: ')
print (sorted_arr[::-1])

Reverse Array: 
[7000 1900  600  500  400  300  300  200  100]


In [120]:
print('Last Five Elements')
print(sorted_arr[-5:])

Last Five Elements
[ 400  500  600 1900 7000]


In [122]:
print('Slicing Done')

Slicing Done
