In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel('students.xlsx')
print(df)

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92


In [3]:
marks=df['Marks'].to_numpy()
print('Numpy Array of Marks')
print(marks)

Numpy Array of Marks
[85 90 78 92]


In [4]:
print('Highest Marks',np.max(marks))

Highest Marks 92


In [5]:
print('Lowest Marks',np.min(marks))

Lowest Marks 78


In [6]:
print('Average Marks',np.mean(marks))

Average Marks 86.25


# .loc: Label Based
# .iloc: Index Based

In [13]:
print('Original Dataframe')
print(df)
print('Location : Label based')
print(df.loc[2,['Name','Marks']])

Original Dataframe
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
Location : Label based
Name     Bob
Marks     78
Name: 2, dtype: object


In [16]:
print('Original Dataframe')
print(df)
print('Location : Index based')
print(df.iloc[3,[0,2]])

Original Dataframe
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
Location : Index based
Name     Sara
Marks      92
Name: 3, dtype: object


# Axis in NumPy : 
    1.Axis 0: vertical direction: works column wise
    2.Axis 1: horizontal direction: works row-wise

# we have 2 student marks in 3 subjects
    [[45,50,49],[30,45,49]]

In [20]:
marks_arr=np.array([[5,2,9],[10,40,60]])
print(marks_arr)

[[ 5  2  9]
 [10 40 60]]


In [21]:
print('sum down each column',np.sum(marks_arr,axis=0))

sum down each column [15 42 69]


In [22]:
print('sum down each row',np.sum(marks_arr,axis=1))

sum down each row [ 16 110]


In [23]:
print('Numpy Array of Marks')
print(marks)

Numpy Array of Marks
[85 90 78 92]


In [24]:
print(df)

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92


# find the students name who got the highest marks

In [27]:
topper=df.loc[df['Marks'].idxmax(),'Name']
print(topper)

Sara


In [26]:
bottomest=df.loc[df['Marks'].idxmin(),'Name']
print(bottomest)

Bob


# Next example using iloc

In [28]:
topIndex=df['Marks'].idxmax()
topStudent=df.iloc[topIndex,df.columns.get_loc('Name')]
print('Topper of the class is: ',topStudent)

Topper of the class is:  Sara
